dsu:
	@mkdir -p bin
	gcc -Wall -Werror dsu.cpp -o bin/dsu

hash:
	@mkdir -p bin
	gcc -Wall -Werror -std=c++11 -lstdc++ hash.cpp -o bin/hash


flow:
	@mkdir -p bin
	gcc -Wall -Werror -std=c++11 -lstdc++ flow.cpp -o bin/flow


djikstras:
	@mkdir -p bin
	gcc -Wall -Werror -std=c++11 -lstdc++ djikstras.cpp -o bin/djistras


milner-rabin:
	@mkdir -p bin
	gcc -g -Wall -Werror -std=c++11 -lstdc++ milner-rabin.cpp -o bin/milner-rabin
